[package]
name = "hyprsunsetauto"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
